//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArvitumNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminationBackPhoto
    {
        public int Id { get; set; }
        public int ExaminationId { get; set; }
        public string FileNameLeft { get; set; }
        public string TitleLeft { get; set; }
        public byte[] ImageDataLeft { get; set; }
        public string FileNameRight { get; set; }
        public string TitleRight { get; set; }
        public byte[] ImageDataRight { get; set; }
        public short X11L { get; set; }
        public short X12L { get; set; }
        public short Y12L { get; set; }
        public short X11R { get; set; }
        public short X12R { get; set; }
        public short Y12R { get; set; }
        public short X21L { get; set; }
        public short Y21L { get; set; }
        public short X21R { get; set; }
        public short Y21R { get; set; }
    
        public virtual Examination Examination { get; set; }
    }
}
